import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer'

// Register fonts if needed (optional for basic usage, but good for polish)
// Font.register({ family: 'Inter', src: '...' }) 

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Helvetica',
        lineHeight: 1.5,
        color: '#1f2937'
    },
    header: {
        marginBottom: 30,
        borderBottom: '1px solid #e5e7eb',
        paddingBottom: 20
    },
    title: {
        fontSize: 24,
        fontFamily: 'Helvetica-Bold',
        marginBottom: 8,
        color: '#111827'
    },
    subtitle: {
        fontSize: 14,
        color: '#4b5563'
    },
    section: {
        marginBottom: 15
    },
    text: {
        fontSize: 12,
        marginBottom: 8,
        textAlign: 'justify'
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 10,
        color: '#9ca3af',
        borderTop: '1px solid #e5e7eb',
        paddingTop: 10
    }
})

interface GuidelinesPDFProps {
    tournament: {
        name: string
        startDate: Date | string
        venue?: string | null
    }
    content: string
}

export default function GuidelinesPDF({ tournament, content }: GuidelinesPDFProps) {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <Text style={styles.title}>{tournament.name.toUpperCase()}</Text>
                    <Text style={styles.subtitle}>OFFICIAL TOURNAMENT GUIDELINES</Text>
                    <Text style={{ ...styles.subtitle, marginTop: 4, fontSize: 10 }}>
                        {new Date(tournament.startDate).toLocaleDateString()} • {tournament.venue || 'Venue TBA'}
                    </Text>
                </View>

                <View style={styles.section}>
                    {content.split('\n').map((line, i) => (
                        line.trim() !== '' ? (
                            <Text key={i} style={styles.text}>{line}</Text>
                        ) : (
                            <View key={i} style={{ height: 10 }} />
                        )
                    ))}
                </View>

                <View style={styles.footer}>
                    <Text>Generated by KTM Manager • {new Date().getFullYear()}</Text>
                </View>
            </Page>
        </Document>
    )
}
