export const COUNTRIES = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
    "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia",
    "Denmark", "Djibouti", "Dominica", "Dominican Republic",
    "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Fiji", "Finland", "France",
    "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
    "Haiti", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
    "Jamaica", "Japan", "Jordan",
    "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway",
    "Oman",
    "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar",
    "Romania", "Russia", "Rwanda",
    "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
    "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
    "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
    "Yemen",
    "Zambia", "Zimbabwe"
];

// Comprehensive country name → 3-letter code mapping (IOC/ISO-style)
const COUNTRY_CODE_MAP: Record<string, string> = {
    'afghanistan': 'AFG',
    'albania': 'ALB',
    'algeria': 'ALG',
    'andorra': 'AND',
    'angola': 'ANG',
    'antigua and barbuda': 'ANT',
    'argentina': 'ARG',
    'armenia': 'ARM',
    'australia': 'AUS',
    'austria': 'AUT',
    'azerbaijan': 'AZE',
    'bahamas': 'BAH',
    'bahrain': 'BRN',
    'bangladesh': 'BAN',
    'barbados': 'BAR',
    'belarus': 'BLR',
    'belgium': 'BEL',
    'belize': 'BIZ',
    'benin': 'BEN',
    'bhutan': 'BHU',
    'bolivia': 'BOL',
    'bosnia and herzegovina': 'BIH',
    'botswana': 'BOT',
    'brazil': 'BRA',
    'brunei': 'BRU',
    'bulgaria': 'BUL',
    'burkina faso': 'BUR',
    'burundi': 'BDI',
    'cabo verde': 'CPV',
    'cambodia': 'CAM',
    'cameroon': 'CMR',
    'canada': 'CAN',
    'central african republic': 'CAF',
    'chad': 'CHA',
    'chile': 'CHI',
    'china': 'CHN',
    'colombia': 'COL',
    'comoros': 'COM',
    'congo': 'CGO',
    'costa rica': 'CRC',
    'croatia': 'CRO',
    'cuba': 'CUB',
    'cyprus': 'CYP',
    'czechia': 'CZE',
    'denmark': 'DEN',
    'djibouti': 'DJI',
    'dominica': 'DMA',
    'dominican republic': 'DOM',
    'ecuador': 'ECU',
    'egypt': 'EGY',
    'el salvador': 'ESA',
    'equatorial guinea': 'GEQ',
    'eritrea': 'ERI',
    'estonia': 'EST',
    'eswatini': 'SWZ',
    'ethiopia': 'ETH',
    'fiji': 'FIJ',
    'finland': 'FIN',
    'france': 'FRA',
    'gabon': 'GAB',
    'gambia': 'GAM',
    'georgia': 'GEO',
    'germany': 'GER',
    'ghana': 'GHA',
    'greece': 'GRE',
    'grenada': 'GRN',
    'guatemala': 'GUA',
    'guinea': 'GUI',
    'guinea-bissau': 'GBS',
    'guyana': 'GUY',
    'haiti': 'HAI',
    'honduras': 'HON',
    'hungary': 'HUN',
    'iceland': 'ISL',
    'india': 'IND',
    'indonesia': 'INA',
    'iran': 'IRI',
    'iraq': 'IRQ',
    'ireland': 'IRL',
    'israel': 'ISR',
    'italy': 'ITA',
    'jamaica': 'JAM',
    'japan': 'JPN',
    'jordan': 'JOR',
    'kazakhstan': 'KAZ',
    'kenya': 'KEN',
    'kiribati': 'KIR',
    'korea, north': 'PRK',
    'korea, south': 'KOR',
    'kosovo': 'KOS',
    'kuwait': 'KUW',
    'kyrgyzstan': 'KGZ',
    'laos': 'LAO',
    'latvia': 'LAT',
    'lebanon': 'LBN',
    'lesotho': 'LES',
    'liberia': 'LBR',
    'libya': 'LBA',
    'liechtenstein': 'LIE',
    'lithuania': 'LTU',
    'luxembourg': 'LUX',
    'madagascar': 'MAD',
    'malawi': 'MAW',
    'malaysia': 'MAS',
    'maldives': 'MDV',
    'mali': 'MLI',
    'malta': 'MLT',
    'marshall islands': 'MHL',
    'mauritania': 'MTN',
    'mauritius': 'MRI',
    'mexico': 'MEX',
    'micronesia': 'FSM',
    'moldova': 'MDA',
    'monaco': 'MON',
    'mongolia': 'MGL',
    'montenegro': 'MNE',
    'morocco': 'MAR',
    'mozambique': 'MOZ',
    'myanmar': 'MYA',
    'namibia': 'NAM',
    'nauru': 'NRU',
    'nepal': 'NEP',
    'netherlands': 'NED',
    'new zealand': 'NZL',
    'nicaragua': 'NCA',
    'niger': 'NIG',
    'nigeria': 'NGR',
    'north macedonia': 'MKD',
    'norway': 'NOR',
    'oman': 'OMA',
    'pakistan': 'PAK',
    'palau': 'PLW',
    'palestine': 'PLE',
    'panama': 'PAN',
    'papua new guinea': 'PNG',
    'paraguay': 'PAR',
    'peru': 'PER',
    'philippines': 'PHI',
    'poland': 'POL',
    'portugal': 'POR',
    'qatar': 'QAT',
    'romania': 'ROU',
    'russia': 'RUS',
    'rwanda': 'RWA',
    'saint kitts and nevis': 'SKN',
    'saint lucia': 'LCA',
    'saint vincent and the grenadines': 'VIN',
    'samoa': 'SAM',
    'san marino': 'SMR',
    'sao tome and principe': 'STP',
    'saudi arabia': 'KSA',
    'senegal': 'SEN',
    'serbia': 'SRB',
    'seychelles': 'SEY',
    'sierra leone': 'SLE',
    'singapore': 'SGP',
    'slovakia': 'SVK',
    'slovenia': 'SLO',
    'solomon islands': 'SOL',
    'somalia': 'SOM',
    'south africa': 'RSA',
    'south sudan': 'SSD',
    'spain': 'ESP',
    'sri lanka': 'SRI',
    'sudan': 'SUD',
    'suriname': 'SUR',
    'sweden': 'SWE',
    'switzerland': 'SUI',
    'syria': 'SYR',
    'taiwan': 'TPE',
    'tajikistan': 'TJK',
    'tanzania': 'TAN',
    'thailand': 'THA',
    'timor-leste': 'TLS',
    'togo': 'TOG',
    'tonga': 'TGA',
    'trinidad and tobago': 'TTO',
    'tunisia': 'TUN',
    'turkey': 'TUR',
    'turkmenistan': 'TKM',
    'tuvalu': 'TUV',
    'uganda': 'UGA',
    'ukraine': 'UKR',
    'united arab emirates': 'UAE',
    'united kingdom': 'GBR',
    'united states': 'USA',
    'uruguay': 'URU',
    'uzbekistan': 'UZB',
    'vanuatu': 'VAN',
    'vatican city': 'VAT',
    'venezuela': 'VEN',
    'vietnam': 'VIE',
    'yemen': 'YEM',
    'zambia': 'ZAM',
    'zimbabwe': 'ZIM',
    // Common aliases
    'south korea': 'KOR',
    'north korea': 'PRK',
    'korea': 'KOR',
    'hong kong': 'HKG',
    'czech republic': 'CZE',
    'usa': 'USA',
    'uk': 'GBR',
    'uae': 'UAE',
}

/**
 * Convert a country name to its 3-letter code (IOC-style).
 * Falls back to the first 3 letters uppercased if not found.
 */
export function countryToCode(country: string | null | undefined): string {
    if (!country) return 'UNK'
    const normalized = country.toLowerCase().trim()
    return COUNTRY_CODE_MAP[normalized] || country.replace(/\s+/g, '').slice(0, 3).toUpperCase()
}
